language: python

cache: pip

branches:
  only:
  - master

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip==9.0.1
  - pip install .[test]

script:
  - coverage run setup.py test

after_success:
  coveralls
