language: python

cache: pip

branches:
  only:
  - master

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip==9.0.1
  - pip install .[test]

script:
  - isort --diff --check-only -q
  - flake8 .
  - coverage run -m pytest

after_success:
  coveralls
